name: Deploy

on:
  push:
    branches: [prd]

jobs:
    standardCheck:
        name: Python Standard Check
        runs-on: ubuntu-latest
        steps:
          - name: Follow Python Standard
            uses: byuawsfhtl/PythonStandardAction@v1.0.6
