name: Deploy

on:
  push:
    branches:
      - prd

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Follow Python Standard
            uses: byuawsfhtl/PythonStandardAction@v1.0.1